name: high-learning-ci
on: 
  workflow_dispatch:
   inputs:
    is_run_fixture:
      description: 'launch this command when first time start server'
      type: boolean
      required: false
      default: false
  push:
env:
  environment: prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Load fixture
        if: ${{ github.event.inputs.is_run_fixture &&  (env.environment == 'dev' || env.environment == 'stage') }}
        run: |
          echo "the fixture command is ran"
