name: high-learning-ci
on: 
  workflow_dispatch:
   inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
      - info
      - warning
      - debug
  push:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Define branch checkout'     
#         required: true
#         default: ${{ github.ref }}
env:
  ENV: develop
  DATABASE_URL: 'mysql:\/\/compy:li_jefw45678sd!@localhost:3306\/compliancy?serverVersion=mariadb-10.6.12&charset=utf8mb4'
  MAIL_HOST: newmail.jinglong.link
  FRONT_DOMAIN: prodss.compliancy.tekos.cloud
  MAILER_USERNAME: app.compliancy.com
  MAILER_FROM: antoine.sauvageot@compliancy.fr
  APP_SECRET: abc
  MAILER_DSN: mail.jinglong.link
  APP_ENV: prod
  


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: user variable
        run: |
          echo '${{ vars.ENV_FILE }}' > .env
          echo "DB_USERNAME=josijfoidsaofis" >> .env
          echo "DB_PASSWORD=jsdofisaifd" >> .env
          echo "DB_HOST=rds.dev.giveabet.local" >> .env
          echo "APP_ENV=dev" >> .env
          echo "FRONT_DOMAIN=iojsoidfj" >> .env
          
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
         name: env
         path: ./
#       - name: Install dependencies
#         uses: php-actions/composer@v6
#         with:
#           php_version: 7.4
#           php_extensions: gd intl bcmath curl xml zip mbstring mysqli iconv pdo_mysql
#           version: 2.x
#       - name: show aws region
#         run: echo ${{ vars.AWS_REGION }}
#       - name: show env
#         run: echo $ENV
          
#       - name: uploard artifact
#         run: zip -r highlearning.zip *
      

         
#       - name: show all files
#         run: ls

