name: high-learning-ci
on: 
  push:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Define branch checkout'     
#         required: true
#         default: ${{ github.ref }}
env:
  ENV: develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Use NodeJS to build
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
#       - name: Install dependencies
#         uses: php-actions/composer@v6
#         with:
#           php_version: 7.4
#           php_extensions: gd intl bcmath curl xml zip mbstring mysqli iconv pdo_mysql
#           version: 2.x
      - name: show aws region
        run: echo ${{ vars.AWS_REGION }}
      - name: show env
        run: echo ${{ env.ENV }}
          
      - name: uploard artifact
        run: zip -r highlearning.zip *
      
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: highlearning
      - name: show all files
        run: ls

