name: high-learning-ci
on: 
  workflow_dispatch:
   inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
      - info
      - warning
      - debug


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: check ansible version
        run: |
          ansible --version
          echo "-------------------"
          python3 --version
        

