name: high-learning-ci
on: 
  workflow_dispatch:
   inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
      - info
      - warning
      - debug
#   push:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Define branch checkout'     
#         required: true
#         default: ${{ github.ref }}
env:
  ENV: develop
  DATABASE_URL: 'mysql:\/\/compy:li_jefw45678sd!@localhost:3306\/compliancy?serverVersion=mariadb-10.6.12&charset=utf8mb4'
  MAIL_HOST: newmail.jinglong.link
  FRONT_DOMAIN: prodss.compliancy.tekos.cloud
  MAILER_USERNAME: app.compliancy.com
  MAILER_FROM: antoine.sauvageot@compliancy.fr
  APP_SECRET: abc
  MAILER_DSN: mail.jinglong.link
  APP_ENV: prod
  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run script
        run: sh ./deploy.sh ${{ secrets.DB_PASSWORD }} ${{ secrets.RQ_PASSWORD }} ${{ secrets.ES_PASSWORD }}
#         env:
#           DB_PASSWORD: db_password
#           RQ_PASSWORD: rq_password
#           ES_PASSWORD: es_password
      - name: show value
        run: cat parameters_prod.yaml
        
#       - name: upload artifact
#         uses: actions/upload-artifact@v3
#         with:
#          name: highlearning
#          path: ./

