name: high-learning-ci
on: 
  push:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Define branch checkout'     
#         required: true
#         default: ${{ github.ref }}
env:
  ENV: develop
  NEW_DATABASE_URL: newdb.jinglong.link
  NEW_MAIL_HOST: newmail.jinglong.link

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Use NodeJS to build
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Replace env vars in file
        # You may pin to the exact commit or the version.
        # uses: falnyr/replace-env-vars-action@e593413a86fd8ef7f6a5861b805c953ef42bc272
        uses: falnyr/replace-env-vars-action@v1.3.2
        with:
          # File for the replacement
          filename: .env
        env:
          DATABASE_URL: db.jinglong.link
          MAIL_PORT: 20
          MAIL_HOST: mail.jinglong.link
          PHP_PORT: 6000
      - name: other replace
        run: |
          sed -i "s/DATABASE_URL=*$/NEW_DATABASE_URL=${{ env.NEW_DATABASE_URL }}/g" .env
          sed -i "s/MAIL_HOST=*$/NEW_MAIL_HOST=${{ env.NEW_MAIL_HOST }}/g" .env
          
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
         name: highlearning
         path: ./
#       - name: Install dependencies
#         uses: php-actions/composer@v6
#         with:
#           php_version: 7.4
#           php_extensions: gd intl bcmath curl xml zip mbstring mysqli iconv pdo_mysql
#           version: 2.x
#       - name: show aws region
#         run: echo ${{ vars.AWS_REGION }}
#       - name: show env
#         run: echo $ENV
          
#       - name: uploard artifact
#         run: zip -r highlearning.zip *
      

         
#       - name: show all files
#         run: ls

