name: Build & Deploy
on: 
  push:
    branches:
      - main
      - feature/*
env:
  PROD_BUILD_PATH: ${GITHUB_WORKSPACE}/www.high-learning.com/src
  PREPROD_BUILD_PATH: ${GITHUB_WORKSPACE}/preprod.high-learning.com/src

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${env.PROD_BUILD_PATH}
    steps:
      - name: create folder
        run: mkdir -p ${env.PROD_BUILD_PATH}
      - name: Checkout
        uses: actions/checkout@v2
      - name: show files
        run: |
          pwd
          echo "-------------"
          ls -la

