name: Build & Deploy
on: 
  push:
    branches:
      - main
      - feature/*
defaults:
  run:
    working-directory: "${{ github.workspace }}/www.high-learning.com/src"
env:
  PROD_BUILD_PATH: "${{ github.workspace }}/www.high-learning.com/src"
  PREPROD_BUILD_PATH: "${{ github.workspace }}/preprod.high-learning.com/src"

jobs:
  build:
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ${{ env.PROD_BUILD_PATH }}
    steps:
#       - name: create folder
#         run:
#           mkdir -p ${{ github.workspace }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.PROD_BUILD_PATH }}
        
      - name: show files
        run: |
          pwd
          echo "-------------"
          ls -la
#         working-directory: ${{ env.PROD_BUILD_PATH }}

